### ISSUE TITLE
[ToDo] List

### ISSUE THREAD

**Issue by lnjX** [Gamerbude/Minetest_TNG#2]
- [ ] 001. Ability to name sheep (after tamed)
- [x] 002. Flint (and flint and steel)
- [x] 003. Bones and bonemeal (bones should be dropped very rarely by zombies or oerrkis) See: #4 
- [ ] 004. Rail corridors or mines
- [ ] 005. Inventory tweaks
- [x] 006. Fence gates and optimize normal fences (collision box)
- [ ] 007. Very expensive and fast tool (maybe a nyan cat multi tool)
- [x] 008. Ruins
- [ ] 009. Make digging more realistic, player first needs a tool before he can dig trees
- [x] **010**. Ores should be more rarely (and maybe deeper)
- [ ] 011. Some different stone types like marble, granite, deepstone, soapstone (in German "Speckstein") ...
- [x] 012. Papyrus Blocks (stair, slab) (needs textures see Texture TODO-List - 001)
- [x] **_013._** Difficult settings (for growing speed, damage of mobs, hunger)
- [x] 014. Achievements / Awards (maybe you should get Xp-Points to unlock new things)
- [x] 015. Tree API
- [x] 016. Rewrite of Farming API (with timers)
- [ ] 017.1 Compost bin and 
- [x] 017.2 garden soil (on that plants should grow faster)
- [ ] 018. Skins
- [x] 019. Furniture (chair with sitting func., some decos., ...)
- [ ] 020. Very very rarely huge trees
- [ ] 021. Trash can, maybe
- [x] 022. Fix Pear
- [ ] 023. Flower pot (decoration) See: https://github.com/pithydon/flowerpots/
- [x] 024. Change the max. stack size [Idea by lightonflux]
- [x] 025. shears
- [x] 026. Strawberries
- [ ] 027. Cabbage
- [ ] 028. Tomatoes
- [ ] 029. Pies (Maybe basing on this mod: https://github.com/tenplus1/pie)
- [ ] 030. Cauldron for cooking soups (Maybe basing on this: https://github.com/kilbith/xdecor/blob/master/cooking.lua)
- [ ] 031. Simple enchanting (Sword/Axe/Pickaxe/Shovel Level 1, 2, 3)
- [ ] 032. Cutting board and knife for making salads
- [ ] 033. Wool / cloth sounds
- [x] 034. Lettuce (for making salads)
- [ ] 035. Zombies can kill sheep
- [ ] 036. Playereffects and Pep (maybe), then vessels would make sense https://forum.minetest.net/viewtopic.php?f=11&t=10222
- [ ] 037. Mushroom node boxes and maybe a "RIESENPILZ"
- [x] 038. Frozen Zombies (in snow biomes)
- [x] 039. Salt ore, block
- [ ] 040. Better eating (eat something only after one/two seconds), don't eat if you're full
- [ ] 041. Nyan Cat Rainbow Tools
- [ ] 042. Add seasons with different leaves textures
- [ ] 043. Add function to register subnode registration (for using with register = {["slab"] = true, ["stair"] = true})
- [ ] 044. poplar trees or any other high tree
- [ ] 045. (Japanese) Paper Walls (using Pane API)
- [ ] 046. Chisel API (to register many different variants of a node, craftable with chisel)
- [ ] 047. Music ([freesound.org](https://freesound.org/people/ShadyDave/sounds/325647/), [freesound.org](https://freesound.org/people/ShadyDave/sounds/325611/))
- [ ] 048. black ghosts in caves, blue ghosts in snow biomes
- [ ] 050. Zombie Jerky (from rotten flesh + 2 salt)
- [ ] 051. Wasteland/Dead biome
- [x] 052. Food: override minetest.item_eat for mod compatibility
- [x] 053. Move legacy/aliases into separate mod
- [ ] 054. Make maple wood brighter than normal
- [x] 055. [DOC] clean up: tree growing funcs,  add missing apis/funcs/vars
- [ ] 056. Bandages to heal, need longer to regenerate by full hunger bar
- [ ] 057. purple blooming lavender grassland biome
- [ ] 058. birches with a thin trunk (and connected drawtype )
- [ ] 059. Lava/Water Spots in Obsidian Glass
- [ ] 060. some different grass types (eg. switch grass)
- [ ] 061. Helmet Lamp (armor), should light up the area around you
- [ ] 062. some more flowers (Daisies, clovers)
- [ ] 063. Let also lava buckets light up the area around you when wield

**_Italic-bold_** text means that it is in process and **bold** text means that this is more important or should be done quickly.

Also see the Texture TODO-List: #5

Everything I have in mind I'll write here. If you want, you can suggest own ideas!
**Please write what you think about these ideas (write which idea)!** :smile_cat: 

Everything that is off-topic will be removed!

**Comment by fridolin2** [comment]
Nice

**Comment by mbblp** [comment]
fences + fence gates  are not conect

**Comment by kilbith** [comment]
Just a note : if you use my code from X-Decor or even slightly modify it, proper credits are expected since it's GPLv3.

**Comment by LNJ2** [comment]
@kilbith Don't worry I will take into account the license, if I use your code. :)

**Comment by LNJ2** [comment]
@kilbith See this part of the GPL: https://github.com/kilbith/xdecor/blob/master/LICENSE#L637-L658, you didn't added this anywhere in your mod(s).

But of course I accept the license!

**Comment by kilbith** [comment]
The text mention this is something optional, the license of course applies to all code files.

**Comment by LNJ2** [comment]
@kilbith I won't deny that, but it is recommended to have it or something like that:
```
License for Code
----------------

Copyright (C) 2010-2013 Your Name <emailaddress>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 2.1 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

License for Textures, Models and Sounds
---------------------------------------

CC-BY-SA 3.0 UNPORTED. Created by Your Name
```
Okay that was from rubenwardys modding book: http://rubenwardy.com/minetest_modding_book/chapters/releasing.html

**Comment by mbblp** [comment]
I found these 2 beautiful piano loops so I would suggest that you can add music .
here are the links.[]( https://freesound.org/people/ShadyDave/sounds/325647/)
                             [](https://freesound.org/people/ShadyDave/sounds/325611/)

**Comment by sefsh** [comment]
Regarding 047 I advise to check out http://incompetech.com/music/royalty-free/index.html for high quality music. One could probably find appropriate tracks for all biomes.

**Comment by lnjX** [comment]
@yusf Thank you. I'm sure we will use some of them.

**Comment by sefsh** [comment]
- [ ] 064. Hoppers 👍

**Comment by lnjX** [comment]
@yusf If you want (and you've know/have a good stable mod) feel free to make a PR (everything should be moved into default of course).
