### ISSUE TITLE
[ToDo] Texture TODO-List

### ISSUE THREAD

**Issue by lnjX** [Gamerbude/Minetest_TNG#5]
Here are some textures that have to be done for some nodes/items/...!
If someone would like to do them please post it here and show them in the New Textures (or a new) issue! :smile:
- [x] 001. Papyrus Block (side, top) (idea based on bambus)
- [ ] 002. Inventory, Chest, Furnace BGs [Reserved by fridolin2]
- [x] 003. Strawberries [fridolin2]
- [x] 004. Cabbage [fridolin2]
- [x] 005. Tomatoes [fridolin2]
- [x] 006. Dry Dirt [fridolin2]
- [x] 007. Frozen Zombie [fridolin2]
- [x] 008. Salt, Salt Ore, Salt Block [fridolin2]
- [x] 009. Roll with Fried Egg [LNJ2]
- [ ] 010. Zombie Jerkey
- [ ] 011. Season: all leaves, grass, flowers (maybe) ... in all seasons

**Comment by JBBgameich** [comment]
What about this Papyrus Block textures?
![default_bamboo_light](https://cloud.githubusercontent.com/assets/13609393/13676221/3f2dbcfa-e6e5-11e5-91fd-1985cbee5e99.png)
![default_bamboo](https://cloud.githubusercontent.com/assets/13609393/13676222/3f36ddbc-e6e5-11e5-9610-27a0cd13fd0a.png)

**Comment by LNJplus** [comment]
I think the textures should be green and don't forget we need a top texture too. (And its not bamboo its papyrus!)

**Comment by mbblp** [comment]
green?
i think the textures are good

**Comment by LNJplus** [comment]
So ich schreib jetzt einfach so auf Deutsch (sollte aber nicht standard werden)
Wenn man einen gelben Block braucht kann man straw nehmen deswegen finde ich es unnoetig noch einen gelben hinzuzufuegen. Ausserdem muessten dann die normalen papyri auch gelb sein

**Comment by JBBgameich** [comment]
Inside the trunks Papyrus is not green I think....
Bamboo is green outside too and inside lightbrown. 
![images](https://cloud.githubusercontent.com/assets/13609393/13676791/85e6630c-e6e7-11e5-8056-033757fdf5af.jpg)
![bamboo](https://cloud.githubusercontent.com/assets/13609393/13676793/89c3e5ee-e6e7-11e5-8aa0-3d67cbee02ad.jpg)

And I think the trunks of Bamboo and Papyru are very simular.
But here is a green variation of the texture:
![default_papyrus_block_green](https://cloud.githubusercontent.com/assets/13609393/13676972/5d3dd006-e6e8-11e5-95cc-fc6e0925d830.png)

**Comment by LNJplus** [comment]
But you cann't see how it looks inside! It's normal papyrus but just bundled in size of a block!

**Comment by JBBgameich** [comment]
Ah, you mean a bundle! In your description you don’t said that.

**Comment by LNJplus** [comment]
I thought that it would be obviously that you don't cut open the papyrus.

**Comment by JBBgameich** [comment]
I will start to make a Bg (for workbench too), but what should it look like? (wood, stone, wool....)

**Comment by LNJplus** [comment]
THIS ISSUE IS ONLY FOR DISCUSSING WHICH TEXTURES ARE NEEDED AND WHICH NOT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by fridolin2** [comment]
I want to make the inventorys for some blocks but after the other things

**Comment by LNJ2** [comment]
Yes, I can add you.

**Comment by fridolin2** [comment]
I make the dry dirt texture also

**Comment by fridolin2** [comment]
Wenn noch mehr anliegt ich mache es

**Comment by mieu12** [comment]
I can do the Zombie Jerky.
